### ISSUE TITLE
analyze and deep includes subtitles

### ISSUE THREAD

**Issue by PiscisSwimeatus** [ajkis/scripts#13]
Analyze and deep includes subtitles, so the scripts keeps listing and scanning the same files over and over again. The items should also be grouped so it does not rescan the same item multiple times.

**Comment by ajkis** [comment]
Hmm the subs are not in the list

**Comment by PiscisSwimeatus** [comment]
Just dobbel checked and you are right, they are not. Sorry. You should still group the query though :)
