### ISSUE TITLE
 $LD_LIBRARY_PATH/usr/lib/plexmediaserver/Plex\ Media\ Scanner

### ISSUE THREAD

**Issue by DerUntote** [ajkis/scripts#26]
I saw this error several times in your scrips. 
example 
https://github.com/ajkis/scripts/blob/master/plex/plex-scan-new.sh

export LD_LIBRARY_PATH=/usr/lib/plexmediaserver
[...]
 $LD_LIBRARY_PATH/usr/lib/plexmediaserver/Plex\ Media\ Scanner

should be 
export LD_LIBRARY_PATH=/usr/lib/plexmediaserver
 $LD_LIBRARY_PATH/Plex\ Media\ Scanner

**Comment by ajkis** [comment]
thanks, fixed it

**Comment by DerUntote** [comment]
Thanks
