### ISSUE TITLE
Script Leaves Behind Folders

### ISSUE THREAD

**Issue by darrylmorley** [ajkis/scripts#51]
Hi,

I'm using your rclone-upload script which does the job well, apart from leaving behind a ton of empty folders.

Am I doing something wrong or is there something I can edit to ensure the folders are removed please?

Thanks

**Comment by ajkis** [comment]
Its actually rclone not removing empty folders but you could add to script after rclone line 
`find /path/movies/** -type d -empty -mmin +10 -delete`

**Comment by darrylmorley** [comment]
Thanks

**Comment by if1mad** [comment]
@darrylmorley https://rclone.org/commands/rclone_rmdirs/

Stick that on the end of the upload command
